theme: jekyll-theme-slate
title: Welcome to Zhaoxia (Cathy) Qian's homepage!

# Build settings
baseurl: /blog # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/
